language: bash

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

before_script:
  - sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu utopic main universe"
  - sudo apt-get -y update
  - sudo apt-get -y install shellcheck

script:
  - shellcheck setup.sh
  - bats test/*.bats

notifications:
  email: false

branches:
  only:
    - master
